site_name: "KubeBuddy by KubeDeck"
site_url: https://kubebuddy.kubedeck.io
docs_dir: docs
site_dir: site
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # primary: custom
    # accent: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kubedeckio/kubebuddy
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2026 KubeDeck

repo_url: https://github.com/kubedeckio/kubebuddy

edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - CLI: 
      - Overview: cli/index.md
      - PowerShell: cli/powershell-usage.md
      - Docker: cli/docker-usage.md
      - Prometheus Integration: cli/prometheus-integration.md
      - Config File: cli/kubebuddy-config.md
      - Checks: cli/checks.md
      - AKS Best Practices: cli/aks-best-practice-checks.md
      - AKS Automatic Migration Readiness: cli/aks-automatic-migration-readiness.md
      - Logging Output: cli/logging-output.md
      - Radar Integration (Pro): cli/kubebuddy-radar-cli-integration.md
  - Radar:
      - Overview: radar/index.md
      - Getting Started: radar/getting-started.md
      - CLI Integration: radar/cli-integration.md
      - Cluster Reports (Pro): radar/cluster-reports.md
      - Cluster Configs (Pro): radar/cluster-configs.md
      - API Reference: radar/api-reference.md
  - Creating Checks: creating-Checks.md
  - Contributing: contributing.md
  - Release Process: releaseprocess.md
  - Changelog: changelog.md
  - KubeDeck: https://kubedeck.io

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tabbed:
       alternate_style: true

plugins:
  - search
